BEGIN;

-- ============================================================
-- FIDELIDADE DE CLIENTES
-- ============================================================
-- Regra comercial:
--
-- R$ 5,00 em produtos = 1 ponto
-- 500 pontos = R$ 5,00 de desconto
--
-- Pontos são creditados quando o pedido é entregue.
-- O mesmo pedido não pode pontuar duas vezes.
-- Resgates são vinculados ao pedido quando utilizados.
-- ============================================================


-- ============================================================
-- 1. CAMPOS DE FIDELIDADE DO CLIENTE
-- ============================================================

ALTER TABLE public.clientes
ADD COLUMN IF NOT EXISTS pontos_saldo integer
NOT NULL DEFAULT 0;

ALTER TABLE public.clientes
ADD COLUMN IF NOT EXISTS fidelidade_progresso_centavos integer
NOT NULL DEFAULT 0;


-- ============================================================
-- 2. VALIDAÇÕES DO CLIENTE
-- ============================================================

DO $$
BEGIN

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.clientes'::regclass
      AND conname = 'clientes_pontos_saldo_nao_negativo'
  ) THEN

    ALTER TABLE public.clientes
    ADD CONSTRAINT clientes_pontos_saldo_nao_negativo
    CHECK (
      pontos_saldo >= 0
    );

  END IF;

END
$$;


DO $$
BEGIN

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.clientes'::regclass
      AND conname = 'clientes_fidelidade_progresso_valido'
  ) THEN

    ALTER TABLE public.clientes
    ADD CONSTRAINT clientes_fidelidade_progresso_valido
    CHECK (
      fidelidade_progresso_centavos >= 0
      AND fidelidade_progresso_centavos < 500
    );

  END IF;

END
$$;


-- ============================================================
-- 3. CAMPOS DE FIDELIDADE DO PEDIDO
-- ============================================================

ALTER TABLE public.pedidos
ADD COLUMN IF NOT EXISTS desconto_fidelidade numeric(12, 2)
NOT NULL DEFAULT 0;

ALTER TABLE public.pedidos
ADD COLUMN IF NOT EXISTS pontos_fidelidade_usados integer
NOT NULL DEFAULT 0;


-- ============================================================
-- 4. VALIDAÇÕES DA FIDELIDADE DO PEDIDO
-- ============================================================

DO $$
BEGIN

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.pedidos'::regclass
      AND conname = 'pedidos_desconto_fidelidade_valido'
  ) THEN

    ALTER TABLE public.pedidos
    ADD CONSTRAINT pedidos_desconto_fidelidade_valido
    CHECK (
      desconto_fidelidade >= 0
    );

  END IF;

END
$$;


DO $$
BEGIN

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.pedidos'::regclass
      AND conname = 'pedidos_pontos_fidelidade_validos'
  ) THEN

    ALTER TABLE public.pedidos
    ADD CONSTRAINT pedidos_pontos_fidelidade_validos
    CHECK (
      pontos_fidelidade_usados >= 0
      AND MOD(pontos_fidelidade_usados, 500) = 0
    );

  END IF;

END
$$;


DO $$
BEGIN

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.pedidos'::regclass
      AND conname = 'pedidos_fidelidade_coerente'
  ) THEN

    ALTER TABLE public.pedidos
    ADD CONSTRAINT pedidos_fidelidade_coerente
    CHECK (
      desconto_fidelidade =
        (pontos_fidelidade_usados / 500) * 5
    );

  END IF;

END
$$;


-- ============================================================
-- 5. EXTRATO DE FIDELIDADE
-- ============================================================

CREATE TABLE IF NOT EXISTS public.fidelidade_movimentacoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  created_at timestamptz NOT NULL DEFAULT now(),

  cliente_id bigint NOT NULL
    REFERENCES public.clientes(id),

  pedido_id bigint
    REFERENCES public.pedidos(id),

  tipo text NOT NULL,

  pontos integer NOT NULL,

  valor_referencia numeric(12, 2),

  observacao text,

  CONSTRAINT fidelidade_movimentacoes_tipo_valido
  CHECK (
    tipo IN (
      'credito_pedido',
      'resgate',
      'ajuste_credito',
      'ajuste_debito'
    )
  )
);


-- ============================================================
-- 6. REGRA DOS VALORES DAS MOVIMENTAÇÕES
-- ============================================================
-- credito_pedido pode registrar 0 pontos quando a compra
-- apenas aumenta o progresso abaixo de R$ 5.
-- ============================================================

ALTER TABLE public.fidelidade_movimentacoes
DROP CONSTRAINT IF EXISTS
fidelidade_movimentacoes_pontos_validos;


ALTER TABLE public.fidelidade_movimentacoes
ADD CONSTRAINT fidelidade_movimentacoes_pontos_validos
CHECK (
  (tipo = 'credito_pedido' AND pontos >= 0)
  OR
  (tipo = 'resgate' AND pontos < 0)
  OR
  (tipo = 'ajuste_credito' AND pontos > 0)
  OR
  (tipo = 'ajuste_debito' AND pontos < 0)
);


-- ============================================================
-- 7. PROTEÇÃO CONTRA CRÉDITO DUPLICADO
-- ============================================================

CREATE UNIQUE INDEX IF NOT EXISTS
fidelidade_credito_pedido_unique
ON public.fidelidade_movimentacoes (pedido_id)
WHERE
  tipo = 'credito_pedido'
  AND pedido_id IS NOT NULL;


-- ============================================================
-- 8. PROTEÇÃO CONTRA RESGATE DUPLICADO
-- ============================================================

CREATE UNIQUE INDEX IF NOT EXISTS
fidelidade_resgate_pedido_unique
ON public.fidelidade_movimentacoes (pedido_id)
WHERE
  tipo = 'resgate'
  AND pedido_id IS NOT NULL;


-- ============================================================
-- 9. FUNÇÃO DE CRÉDITO AUTOMÁTICO
-- ============================================================
-- Executada quando o pedido entra em "entregue".
--
-- Pontua somente:
--
-- subtotal - desconto_fidelidade
--
-- Taxa de cartão e outras taxas não geram pontos.
-- ============================================================

CREATE OR REPLACE FUNCTION public.processar_fidelidade_pedido_entregue()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_progresso_atual integer;

  v_valor_pedido_centavos integer;

  v_total_acumulado_centavos integer;

  v_pontos_gerados integer;

  v_novo_progresso integer;
BEGIN

  ----------------------------------------------------
  -- Só processa quando entra em "entregue"
  ----------------------------------------------------

  IF NEW.status <> 'entregue'
     OR OLD.status = 'entregue' THEN

    RETURN NEW;

  END IF;


  ----------------------------------------------------
  -- Bloqueia cliente durante o cálculo
  ----------------------------------------------------

  SELECT fidelidade_progresso_centavos
  INTO v_progresso_atual
  FROM public.clientes
  WHERE id = NEW.cliente_id
  FOR UPDATE;


  IF NOT FOUND THEN

    RAISE EXCEPTION
      'CLIENTE_NAO_ENCONTRADO:%',
      NEW.cliente_id;

  END IF;


  ----------------------------------------------------
  -- Impede que um pedido gere pontos duas vezes
  ----------------------------------------------------

  IF EXISTS (
    SELECT 1
    FROM public.fidelidade_movimentacoes
    WHERE pedido_id = NEW.id
      AND tipo = 'credito_pedido'
  ) THEN

    RETURN NEW;

  END IF;


  ----------------------------------------------------
  -- Valor efetivamente pago pelos produtos
  ----------------------------------------------------

  v_valor_pedido_centavos :=
    ROUND(
      GREATEST(
        COALESCE(NEW.subtotal, 0)
        - COALESCE(NEW.desconto_fidelidade, 0),
        0
      ) * 100
    )::integer;


  ----------------------------------------------------
  -- Soma resto anterior
  ----------------------------------------------------

  v_total_acumulado_centavos :=
    v_progresso_atual
    + v_valor_pedido_centavos;


  ----------------------------------------------------
  -- R$ 5,00 = 1 ponto
  ----------------------------------------------------

  v_pontos_gerados :=
    FLOOR(
      v_total_acumulado_centavos::numeric / 500
    )::integer;


  ----------------------------------------------------
  -- Guarda resto abaixo de R$ 5
  ----------------------------------------------------

  v_novo_progresso :=
    MOD(
      v_total_acumulado_centavos,
      500
    );


  ----------------------------------------------------
  -- Atualiza cliente
  ----------------------------------------------------

  UPDATE public.clientes
  SET
    pontos_saldo =
      pontos_saldo + v_pontos_gerados,

    fidelidade_progresso_centavos =
      v_novo_progresso

  WHERE id = NEW.cliente_id;


  ----------------------------------------------------
  -- Registra extrato
  ----------------------------------------------------

  INSERT INTO public.fidelidade_movimentacoes (
    cliente_id,
    pedido_id,
    tipo,
    pontos,
    valor_referencia,
    observacao
  )
  VALUES (
    NEW.cliente_id,
    NEW.id,
    'credito_pedido',
    v_pontos_gerados,

    GREATEST(
      COALESCE(NEW.subtotal, 0)
      - COALESCE(NEW.desconto_fidelidade, 0),
      0
    ),

    'Crédito de fidelidade do pedido #'
      || NEW.id
  );


  RETURN NEW;

END;
$function$;


-- ============================================================
-- 10. TRIGGER AO ENTREGAR PEDIDO
-- ============================================================

DROP TRIGGER IF EXISTS
trg_fidelidade_pedido_entregue
ON public.pedidos;


CREATE TRIGGER trg_fidelidade_pedido_entregue
AFTER UPDATE OF status
ON public.pedidos
FOR EACH ROW
WHEN (
  OLD.status IS DISTINCT FROM NEW.status
  AND NEW.status = 'entregue'
)
EXECUTE FUNCTION
public.processar_fidelidade_pedido_entregue();


-- ============================================================
-- 11. FUNÇÃO ADMINISTRATIVA DE RESGATE
-- ============================================================
-- 500 pontos = R$ 5,00
--
-- Não será chamada diretamente pelo checkout.
-- O checkout utiliza o resgate transacional junto ao pedido.
-- ============================================================

CREATE OR REPLACE FUNCTION public.resgatar_pontos_fidelidade(
  p_cliente_id bigint,
  p_pontos_resgatar integer
)
RETURNS TABLE(
  cliente_id bigint,
  pontos_resgatados integer,
  valor_desconto numeric,
  saldo_pontos integer
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_saldo_atual integer;

  v_novo_saldo integer;

  v_valor_desconto numeric(12, 2);
BEGIN

  IF p_pontos_resgatar IS NULL
     OR p_pontos_resgatar <= 0 THEN

    RAISE EXCEPTION
      'PONTOS_RESGATE_INVALIDOS';

  END IF;


  IF MOD(p_pontos_resgatar, 500) <> 0 THEN

    RAISE EXCEPTION
      'PONTOS_RESGATE_DEVE_SER_MULTIPLO_DE_500';

  END IF;


  SELECT pontos_saldo
  INTO v_saldo_atual
  FROM public.clientes
  WHERE id = p_cliente_id
  FOR UPDATE;


  IF NOT FOUND THEN

    RAISE EXCEPTION
      'CLIENTE_NAO_ENCONTRADO:%',
      p_cliente_id;

  END IF;


  IF v_saldo_atual < p_pontos_resgatar THEN

    RAISE EXCEPTION
      'SALDO_PONTOS_INSUFICIENTE:%:%',
      v_saldo_atual,
      p_pontos_resgatar;

  END IF;


  v_valor_desconto :=
    (p_pontos_resgatar / 500) * 5;


  v_novo_saldo :=
    v_saldo_atual - p_pontos_resgatar;


  UPDATE public.clientes
  SET pontos_saldo = v_novo_saldo
  WHERE id = p_cliente_id;


  INSERT INTO public.fidelidade_movimentacoes (
    cliente_id,
    pedido_id,
    tipo,
    pontos,
    valor_referencia,
    observacao
  )
  VALUES (
    p_cliente_id,
    NULL,
    'resgate',
    -p_pontos_resgatar,
    v_valor_desconto,

    'Resgate de fidelidade: R$ '
      || to_char(
        v_valor_desconto,
        'FM999999990.00'
      )
      || ' de desconto'
  );


  RETURN QUERY
  SELECT
    p_cliente_id,
    p_pontos_resgatar,
    v_valor_desconto,
    v_novo_saldo;

END;
$function$;


-- ============================================================
-- 11.1. CORREÇÃO DA FUNÇÃO PRINCIPAL DE PEDIDOS
-- ============================================================
-- Cliente existente mantém o nome canônico do CRM.
-- O nome informado no checkout continua salvo em pedidos.nome_cliente.
-- ============================================================

CREATE OR REPLACE FUNCTION public.criar_pedido_com_estoque(p_nome text, p_telefone text, p_cep text, p_rua text, p_numero text, p_complemento text, p_bairro text, p_referencia text, p_forma_pagamento text, p_troco_para numeric, p_itens jsonb)
 RETURNS TABLE(pedido_id bigint, codigo_acesso uuid, subtotal numeric, taxa_entrega numeric, total numeric)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_cliente_id bigint;
  v_pedido_id bigint;
  v_codigo_acesso uuid;

  v_subtotal numeric := 0;
  v_taxa_entrega numeric := 0;
  v_taxa_cartao numeric := 0;
  v_total numeric := 0;

  v_permite_abaixo_minimo boolean := false;

  v_quantidade_solicitada integer;
  v_quantidade_encontrada integer;

  v_nome_produto text;
  v_estoque_disponivel integer;
  v_quantidade_produto integer;
begin

  ----------------------------------------------------
  -- 1. Valida os itens
  ----------------------------------------------------

  if p_itens is null
     or jsonb_typeof(p_itens) <> 'array'
     or jsonb_array_length(p_itens) = 0 then

    raise exception 'CARRINHO_VAZIO';

  end if;

  if exists (
    select 1
    from jsonb_to_recordset(p_itens)
      as item(id bigint, quantidade integer)
    where item.id is null
       or item.quantidade is null
       or item.quantidade <= 0
  ) then

    raise exception 'ITEM_INVALIDO';

  end if;


  ----------------------------------------------------
  -- 2. Bloqueia os produtos
  ----------------------------------------------------

  perform p.id
  from produtos p
  join (
    select
      item.id as produto_id,
      sum(item.quantidade)::integer as quantidade
    from jsonb_to_recordset(p_itens)
      as item(id bigint, quantidade integer)
    group by item.id
  ) itens
    on itens.produto_id = p.id
  order by p.id
  for update of p;


  ----------------------------------------------------
  -- 3. Confere se todos existem
  ----------------------------------------------------

  select count(*)
  into v_quantidade_solicitada
  from (
    select distinct item.id
    from jsonb_to_recordset(p_itens)
      as item(id bigint, quantidade integer)
  ) solicitados;

  select count(*)
  into v_quantidade_encontrada
  from produtos p
  join (
    select distinct item.id
    from jsonb_to_recordset(p_itens)
      as item(id bigint, quantidade integer)
  ) solicitados
    on solicitados.id = p.id;

  if v_quantidade_encontrada <> v_quantidade_solicitada then
    raise exception 'PRODUTO_NAO_ENCONTRADO';
  end if;


  ----------------------------------------------------
  -- 4. Confere produtos inativos
  ----------------------------------------------------

  select p.nome
  into v_nome_produto
  from produtos p
  join (
    select distinct item.id
    from jsonb_to_recordset(p_itens)
      as item(id bigint, quantidade integer)
  ) solicitados
    on solicitados.id = p.id
  where p.ativo = false
  limit 1;

  if found then
    raise exception 'PRODUTO_INATIVO:%', v_nome_produto;
  end if;


  ----------------------------------------------------
  -- 5. Confere estoque
  ----------------------------------------------------

  select
    p.nome,
    p.estoque,
    itens.quantidade
  into
    v_nome_produto,
    v_estoque_disponivel,
    v_quantidade_produto
  from produtos p
  join (
    select
      item.id as produto_id,
      sum(item.quantidade)::integer as quantidade
    from jsonb_to_recordset(p_itens)
      as item(id bigint, quantidade integer)
    group by item.id
  ) itens
    on itens.produto_id = p.id
  where p.estoque < itens.quantidade
  limit 1;

  if found then
    raise exception
      'ESTOQUE_INSUFICIENTE:%:%',
      v_nome_produto,
      v_estoque_disponivel;
  end if;


  ----------------------------------------------------
  -- 6. Calcula subtotal
  ----------------------------------------------------

  select coalesce(
    sum(
      (
        case
          when p.em_promocao = true
            and p.preco_promocional is not null
          then p.preco_promocional
          else p.preco
        end
      ) * itens.quantidade
    ),
    0
  )
  into v_subtotal
  from produtos p
  join (
    select
      item.id as produto_id,
      sum(item.quantidade)::integer as quantidade
    from jsonb_to_recordset(p_itens)
      as item(id bigint, quantidade integer)
    group by item.id
  ) itens
    on itens.produto_id = p.id;


  ----------------------------------------------------
  -- 7. Verifica exceção ao pedido mínimo
  ----------------------------------------------------

  select coalesce(
    bool_or(p.permite_abaixo_minimo),
    false
  )
  into v_permite_abaixo_minimo
  from produtos p
  join (
    select distinct item.id as produto_id
    from jsonb_to_recordset(p_itens)
      as item(id bigint, quantidade integer)
  ) itens
    on itens.produto_id = p.id;


  ----------------------------------------------------
  -- 8. Valida pedido mínimo
  ----------------------------------------------------

  if v_subtotal < 30
     and not v_permite_abaixo_minimo then

    raise exception 'PEDIDO_MINIMO:30';

  end if;


  ----------------------------------------------------
  -- 9. Calcula taxas e total
  ----------------------------------------------------

  v_taxa_entrega := 0;

  if p_forma_pagamento = 'cartao_entrega' then
    v_taxa_cartao := 2;
  else
    v_taxa_cartao := 0;
  end if;

  v_total :=
    v_subtotal
    + v_taxa_entrega
    + v_taxa_cartao;


  ----------------------------------------------------
  -- 10. Reutiliza ou cria cliente pelo telefone
  ----------------------------------------------------

  insert into clientes as c (
    nome,
    telefone
  )
  values (
    trim(p_nome),
    trim(p_telefone)
  )
  on conflict (telefone_normalizado)
  do update
  set
    telefone = excluded.telefone
  returning c.id
  into v_cliente_id;


  ----------------------------------------------------
  -- 11. Cria pedido
  ----------------------------------------------------

  insert into pedidos (
    cliente_id,
    nome_cliente,
    telefone,
    cep,
    rua,
    numero,
    complemento,
    bairro,
    referencia,
    forma_pagamento,
    troco_para,
    subtotal,
    taxa_entrega,
    taxa_cartao,
    total,
    status
  )
  values (
    v_cliente_id,
    trim(p_nome),
    trim(p_telefone),
    trim(p_cep),
    trim(p_rua),
    trim(p_numero),
    nullif(trim(p_complemento), ''),
    trim(p_bairro),
    nullif(trim(p_referencia), ''),
    p_forma_pagamento,

    case
      when p_forma_pagamento = 'dinheiro'
      then p_troco_para
      else null
    end,

    v_subtotal,
    v_taxa_entrega,
    v_taxa_cartao,
    v_total,
    'recebido'
  )
  returning
    id,
    pedidos.codigo_acesso
  into
    v_pedido_id,
    v_codigo_acesso;


  ----------------------------------------------------
  -- 12. Salva itens do pedido
  ----------------------------------------------------

  insert into itens_pedido (
    pedido_id,
    produto_id,
    nome_produto,
    preco_unitario,
    quantidade,
    subtotal
  )
  select
    v_pedido_id,
    p.id,
    p.nome,

    case
      when p.em_promocao = true
        and p.preco_promocional is not null
      then p.preco_promocional
      else p.preco
    end,

    itens.quantidade,

    (
      case
        when p.em_promocao = true
          and p.preco_promocional is not null
        then p.preco_promocional
        else p.preco
      end
    ) * itens.quantidade

  from produtos p
  join (
    select
      item.id as produto_id,
      sum(item.quantidade)::integer as quantidade
    from jsonb_to_recordset(p_itens)
      as item(id bigint, quantidade integer)
    group by item.id
  ) itens
    on itens.produto_id = p.id;


  ----------------------------------------------------
  -- 13. Registra a venda no histórico
  ----------------------------------------------------

  insert into movimentacoes_estoque (
    produto_id,
    pedido_id,
    tipo,
    quantidade,
    estoque_anterior,
    estoque_novo,
    observacao
  )
  select
    p.id,
    v_pedido_id,
    'venda',
    -itens.quantidade,
    p.estoque,
    p.estoque - itens.quantidade,
    'Venda do pedido #' || v_pedido_id

  from produtos p
  join (
    select
      item.id as produto_id,
      sum(item.quantidade)::integer as quantidade
    from jsonb_to_recordset(p_itens)
      as item(id bigint, quantidade integer)
    group by item.id
  ) itens
    on itens.produto_id = p.id;


  ----------------------------------------------------
  -- 14. Baixa o estoque
  ----------------------------------------------------

  update produtos p
  set estoque = p.estoque - itens.quantidade
  from (
    select
      item.id as produto_id,
      sum(item.quantidade)::integer as quantidade
    from jsonb_to_recordset(p_itens)
      as item(id bigint, quantidade integer)
    group by item.id
  ) itens
  where p.id = itens.produto_id;


  ----------------------------------------------------
  -- 15. Retorna pedido criado
  ----------------------------------------------------

  return query
  select
    v_pedido_id,
    v_codigo_acesso,
    v_subtotal,
    v_taxa_entrega,
    v_total;

end;
$function$;


-- ============================================================
-- 12. CRIA PEDIDO COM FIDELIDADE
-- ============================================================
-- Sobrecarga:
--
-- função atual de 11 parâmetros
-- +
-- p_pontos_fidelidade integer
--
-- Toda a criação do pedido, estoque e resgate ocorre
-- dentro da mesma transação PostgreSQL.
-- ============================================================

CREATE OR REPLACE FUNCTION public.criar_pedido_com_estoque(
  p_nome text,
  p_telefone text,
  p_cep text,
  p_rua text,
  p_numero text,
  p_complemento text,
  p_bairro text,
  p_referencia text,
  p_forma_pagamento text,
  p_troco_para numeric,
  p_itens jsonb,
  p_pontos_fidelidade integer
)
RETURNS TABLE(
  pedido_id bigint,
  codigo_acesso uuid,
  subtotal numeric,
  taxa_entrega numeric,
  total numeric
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_resultado record;

  v_cliente_id bigint;

  v_saldo_atual integer;

  v_subtotal numeric;

  v_taxa_entrega numeric;

  v_taxa_cartao numeric;

  v_desconto numeric(12, 2);

  v_total_final numeric(12, 2);
BEGIN

  ----------------------------------------------------
  -- Valida pontos
  ----------------------------------------------------

  IF p_pontos_fidelidade IS NULL
     OR p_pontos_fidelidade < 0 THEN

    RAISE EXCEPTION
      'PONTOS_FIDELIDADE_INVALIDOS';

  END IF;


  IF MOD(p_pontos_fidelidade, 500) <> 0 THEN

    RAISE EXCEPTION
      'PONTOS_FIDELIDADE_DEVE_SER_MULTIPLO_DE_500';

  END IF;


  ----------------------------------------------------
  -- Usa função principal já existente
  ----------------------------------------------------

  SELECT *
  INTO v_resultado
  FROM public.criar_pedido_com_estoque(
    p_nome,
    p_telefone,
    p_cep,
    p_rua,
    p_numero,
    p_complemento,
    p_bairro,
    p_referencia,
    p_forma_pagamento,
    p_troco_para,
    p_itens
  );


  ----------------------------------------------------
  -- Pedido sem resgate
  ----------------------------------------------------

  IF p_pontos_fidelidade = 0 THEN

    RETURN QUERY
    SELECT
      v_resultado.pedido_id,
      v_resultado.codigo_acesso,
      v_resultado.subtotal,
      v_resultado.taxa_entrega,
      v_resultado.total;

    RETURN;

  END IF;


  ----------------------------------------------------
  -- Busca pedido recém-criado
  ----------------------------------------------------

  SELECT
    p.cliente_id,
    p.subtotal,
    p.taxa_entrega,
    p.taxa_cartao

  INTO
    v_cliente_id,
    v_subtotal,
    v_taxa_entrega,
    v_taxa_cartao

  FROM public.pedidos p
  WHERE p.id = v_resultado.pedido_id
  FOR UPDATE;


  IF NOT FOUND THEN

    RAISE EXCEPTION
      'PEDIDO_NAO_ENCONTRADO_APOS_CRIACAO:%',
      v_resultado.pedido_id;

  END IF;


  ----------------------------------------------------
  -- Bloqueia cliente e consulta saldo
  ----------------------------------------------------

  SELECT c.pontos_saldo
  INTO v_saldo_atual
  FROM public.clientes c
  WHERE c.id = v_cliente_id
  FOR UPDATE;


  IF NOT FOUND THEN

    RAISE EXCEPTION
      'CLIENTE_NAO_ENCONTRADO:%',
      v_cliente_id;

  END IF;


  ----------------------------------------------------
  -- Confere saldo
  ----------------------------------------------------

  IF v_saldo_atual < p_pontos_fidelidade THEN

    RAISE EXCEPTION
      'SALDO_PONTOS_INSUFICIENTE:%:%',
      v_saldo_atual,
      p_pontos_fidelidade;

  END IF;


  ----------------------------------------------------
  -- Calcula desconto
  ----------------------------------------------------

  v_desconto :=
    (p_pontos_fidelidade / 500) * 5;


  ----------------------------------------------------
  -- Fidelidade não paga taxas
  ----------------------------------------------------

  IF v_desconto > v_subtotal THEN

    RAISE EXCEPTION
      'DESCONTO_FIDELIDADE_SUPERA_SUBTOTAL:%:%',
      v_desconto,
      v_subtotal;

  END IF;


  ----------------------------------------------------
  -- Novo total
  ----------------------------------------------------

  v_total_final :=
      v_subtotal
    + v_taxa_entrega
    + v_taxa_cartao
    - v_desconto;


  ----------------------------------------------------
  -- Consome pontos
  ----------------------------------------------------

  UPDATE public.clientes
  SET pontos_saldo =
    pontos_saldo - p_pontos_fidelidade
  WHERE id = v_cliente_id;


  ----------------------------------------------------
  -- Atualiza pedido
  ----------------------------------------------------

  UPDATE public.pedidos
  SET
    desconto_fidelidade =
      v_desconto,

    pontos_fidelidade_usados =
      p_pontos_fidelidade,

    total =
      v_total_final

  WHERE id = v_resultado.pedido_id;


  ----------------------------------------------------
  -- Registra resgate no extrato
  ----------------------------------------------------

  INSERT INTO public.fidelidade_movimentacoes (
    cliente_id,
    pedido_id,
    tipo,
    pontos,
    valor_referencia,
    observacao
  )
  VALUES (
    v_cliente_id,
    v_resultado.pedido_id,
    'resgate',
    -p_pontos_fidelidade,
    v_desconto,

    'Resgate de fidelidade no pedido #'
      || v_resultado.pedido_id
      || ': R$ '
      || to_char(
        v_desconto,
        'FM999999990.00'
      )
      || ' de desconto'
  );


  ----------------------------------------------------
  -- Retorno
  ----------------------------------------------------

  RETURN QUERY
  SELECT
    v_resultado.pedido_id,
    v_resultado.codigo_acesso,
    v_subtotal,
    v_taxa_entrega,
    v_total_final;

END;
$function$;


-- ============================================================
-- 13. PEDIDO + FIDELIDADE + IDEMPOTÊNCIA
-- ============================================================

CREATE OR REPLACE FUNCTION public.criar_pedido_com_estoque(
  p_nome text,
  p_telefone text,
  p_cep text,
  p_rua text,
  p_numero text,
  p_complemento text,
  p_bairro text,
  p_referencia text,
  p_forma_pagamento text,
  p_troco_para numeric,
  p_itens jsonb,
  p_pontos_fidelidade integer,
  p_chave_idempotencia uuid
)
RETURNS TABLE(
  pedido_id bigint,
  codigo_acesso uuid,
  subtotal numeric,
  taxa_entrega numeric,
  total numeric
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_pedido_existente record;

  v_resultado record;
BEGIN

  IF p_chave_idempotencia IS NULL THEN

    RAISE EXCEPTION
      'CHAVE_IDEMPOTENCIA_INVALIDA';

  END IF;


  ----------------------------------------------------
  -- Trava chave de idempotência
  ----------------------------------------------------

  PERFORM pg_advisory_xact_lock(
    hashtextextended(
      p_chave_idempotencia::text,
      0
    )
  );


  ----------------------------------------------------
  -- Procura pedido existente
  ----------------------------------------------------

  SELECT
    p.id,
    p.codigo_acesso,
    p.subtotal,
    p.taxa_entrega,
    p.total

  INTO v_pedido_existente

  FROM public.pedidos p

  WHERE p.chave_idempotencia =
    p_chave_idempotencia

  LIMIT 1;


  IF FOUND THEN

    RETURN QUERY
    SELECT
      v_pedido_existente.id,
      v_pedido_existente.codigo_acesso,
      v_pedido_existente.subtotal,
      v_pedido_existente.taxa_entrega,
      v_pedido_existente.total;

    RETURN;

  END IF;


  ----------------------------------------------------
  -- Cria com fidelidade
  ----------------------------------------------------

  SELECT *
  INTO v_resultado
  FROM public.criar_pedido_com_estoque(
    p_nome,
    p_telefone,
    p_cep,
    p_rua,
    p_numero,
    p_complemento,
    p_bairro,
    p_referencia,
    p_forma_pagamento,
    p_troco_para,
    p_itens,
    p_pontos_fidelidade
  );


  ----------------------------------------------------
  -- Vincula chave ao pedido
  ----------------------------------------------------

  UPDATE public.pedidos
  SET chave_idempotencia =
    p_chave_idempotencia
  WHERE id = v_resultado.pedido_id;


  ----------------------------------------------------
  -- Retorno
  ----------------------------------------------------

  RETURN QUERY
  SELECT
    v_resultado.pedido_id,
    v_resultado.codigo_acesso,
    v_resultado.subtotal,
    v_resultado.taxa_entrega,
    v_resultado.total;

END;
$function$;


-- ============================================================
-- 14. PERMISSÕES DE SEGURANÇA
-- ============================================================
-- Funções que consomem pontos só podem ser executadas
-- pelo backend usando service_role.
-- ============================================================

REVOKE ALL
ON FUNCTION public.resgatar_pontos_fidelidade(
  bigint,
  integer
)
FROM PUBLIC;

REVOKE ALL
ON FUNCTION public.resgatar_pontos_fidelidade(
  bigint,
  integer
)
FROM anon, authenticated;

GRANT EXECUTE
ON FUNCTION public.resgatar_pontos_fidelidade(
  bigint,
  integer
)
TO service_role;


REVOKE ALL
ON FUNCTION public.criar_pedido_com_estoque(
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  numeric,
  jsonb,
  integer
)
FROM PUBLIC;

REVOKE ALL
ON FUNCTION public.criar_pedido_com_estoque(
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  numeric,
  jsonb,
  integer
)
FROM anon, authenticated;

GRANT EXECUTE
ON FUNCTION public.criar_pedido_com_estoque(
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  numeric,
  jsonb,
  integer
)
TO service_role;


REVOKE ALL
ON FUNCTION public.criar_pedido_com_estoque(
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  numeric,
  jsonb,
  integer,
  uuid
)
FROM PUBLIC;

REVOKE ALL
ON FUNCTION public.criar_pedido_com_estoque(
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  numeric,
  jsonb,
  integer,
  uuid
)
FROM anon, authenticated;

GRANT EXECUTE
ON FUNCTION public.criar_pedido_com_estoque(
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  numeric,
  jsonb,
  integer,
  uuid
)
TO service_role;
------------------------------------------------------------
-- CANCELAMENTO DE PEDIDO COM ESTORNO DA FIDELIDADE
------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.cancelar_pedido_repor_estoque(
  p_pedido_id bigint
)
RETURNS TABLE(
  id bigint,
  status text
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_status text;
  v_cliente_id bigint;
  v_pontos_fidelidade_usados integer;
  v_desconto_fidelidade numeric(12, 2);
BEGIN

  ----------------------------------------------------
  -- 1. Bloqueia o pedido
  ----------------------------------------------------

  SELECT
    p.status,
    p.cliente_id,
    COALESCE(p.pontos_fidelidade_usados, 0),
    COALESCE(p.desconto_fidelidade, 0)

  INTO
    v_status,
    v_cliente_id,
    v_pontos_fidelidade_usados,
    v_desconto_fidelidade

  FROM public.pedidos AS p

  WHERE p.id = p_pedido_id

  FOR UPDATE;


  IF NOT FOUND THEN
    RAISE EXCEPTION 'PEDIDO_NAO_ENCONTRADO';
  END IF;


  ----------------------------------------------------
  -- 2. Cancelamento idempotente
  ----------------------------------------------------

  IF v_status = 'cancelado' THEN

    RETURN QUERY
    SELECT
      p.id,
      p.status
    FROM public.pedidos AS p
    WHERE p.id = p_pedido_id;

    RETURN;

  END IF;


  ----------------------------------------------------
  -- 3. Entregue não pode ser cancelado
  ----------------------------------------------------

  IF v_status = 'entregue' THEN

    RAISE EXCEPTION
      'PEDIDO_ENTREGUE_NAO_PODE_SER_CANCELADO';

  END IF;


  ----------------------------------------------------
  -- 4. Devolve pontos utilizados
  ----------------------------------------------------

  IF v_pontos_fidelidade_usados > 0 THEN

    UPDATE public.clientes AS c

    SET pontos_saldo =
      c.pontos_saldo
      + v_pontos_fidelidade_usados

    WHERE c.id = v_cliente_id;


    IF NOT FOUND THEN

      RAISE EXCEPTION
        'CLIENTE_NAO_ENCONTRADO:%',
        v_cliente_id;

    END IF;


    INSERT INTO public.fidelidade_movimentacoes (
      cliente_id,
      pedido_id,
      tipo,
      pontos,
      valor_referencia,
      observacao
    )
    VALUES (
      v_cliente_id,
      p_pedido_id,
      'ajuste_credito',
      v_pontos_fidelidade_usados,
      v_desconto_fidelidade,
      'Estorno de fidelidade por cancelamento do pedido #'
        || p_pedido_id
    );

  END IF;


  ----------------------------------------------------
  -- 5. Registra devolução no histórico de estoque
  ----------------------------------------------------

  INSERT INTO public.movimentacoes_estoque (
    produto_id,
    pedido_id,
    tipo,
    quantidade,
    estoque_anterior,
    estoque_novo,
    observacao
  )
  SELECT
    p.id,
    p_pedido_id,
    'cancelamento',
    itens.quantidade_total,
    p.estoque,
    p.estoque + itens.quantidade_total,
    'Cancelamento do pedido #'
      || p_pedido_id

  FROM public.produtos AS p

  JOIN (
    SELECT
      ip.produto_id,
      SUM(ip.quantidade)::integer AS quantidade_total

    FROM public.itens_pedido AS ip

    WHERE ip.pedido_id = p_pedido_id

    GROUP BY ip.produto_id
  ) AS itens
    ON itens.produto_id = p.id;


  ----------------------------------------------------
  -- 6. Devolve estoque
  ----------------------------------------------------

  UPDATE public.produtos AS p

  SET estoque =
    p.estoque + itens.quantidade_total

  FROM (
    SELECT
      ip.produto_id,
      SUM(ip.quantidade)::integer AS quantidade_total

    FROM public.itens_pedido AS ip

    WHERE ip.pedido_id = p_pedido_id

    GROUP BY ip.produto_id
  ) AS itens

  WHERE p.id = itens.produto_id;


  ----------------------------------------------------
  -- 7. Marca como cancelado
  ----------------------------------------------------

  UPDATE public.pedidos AS p

  SET status = 'cancelado'

  WHERE p.id = p_pedido_id;


  ----------------------------------------------------
  -- 8. Retorna
  ----------------------------------------------------

  RETURN QUERY
  SELECT
    p.id,
    p.status

  FROM public.pedidos AS p

  WHERE p.id = p_pedido_id;

END;
$function$;


COMMIT;