-- ============================================================================
-- Depósito do Zé
-- Migration: estoque físico compartilhado
-- Data: 2026-09-18
--
-- Objetivo:
--   Permitir que vários formatos de venda (unidade, promoção, pack etc.)
--   consumam o mesmo estoque físico real.
--
-- Exemplo:
--   240 latões físicos de Brahma 473 ml
--   unidade -> consome 1  -> 240 vendas possíveis
--   promoção 5 -> consome 5 -> 48 vendas possíveis
--   pack 12 -> consome 12 -> 20 vendas possíveis
--
-- Observação:
--   Esta migration versiona a ESTRUTURA e a LÓGICA do recurso.
--   Ela não cadastra produtos específicos nem dados de estoque de produção.
-- ============================================================================


-- ============================================================================
-- 1. TABELAS
-- ============================================================================

create table if not exists public.estoques_compartilhados (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  nome text not null,
  quantidade_total integer not null default 0,
  constraint estoques_compartilhados_quantidade_total_check
    check (quantidade_total >= 0)
);

create unique index if not exists estoques_compartilhados_nome_unique
  on public.estoques_compartilhados (lower(nome));


create table if not exists public.produto_estoque_config (
  produto_id bigint primary key
    references public.produtos(id)
    on delete cascade,

  estoque_compartilhado_id bigint not null
    references public.estoques_compartilhados(id)
    on delete restrict,

  quantidade_por_venda integer not null default 1,

  constraint produto_estoque_config_quantidade_por_venda_check
    check (quantidade_por_venda > 0)
);

create index if not exists produto_estoque_config_estoque_idx
  on public.produto_estoque_config (estoque_compartilhado_id);


create table if not exists public.movimentacoes_estoque_compartilhado (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),

  estoque_compartilhado_id bigint not null
    references public.estoques_compartilhados(id)
    on delete restrict,

  pedido_id bigint null
    references public.pedidos(id)
    on delete set null,

  quantidade_anterior integer not null,
  quantidade_nova integer not null,
  unidades_consumidas integer not null default 0,
  observacao text null
);


-- ============================================================================
-- 2. RLS
-- ============================================================================

alter table public.estoques_compartilhados
  enable row level security;

alter table public.produto_estoque_config
  enable row level security;

alter table public.movimentacoes_estoque_compartilhado
  enable row level security;


-- ============================================================================
-- 3. SINCRONIZAÇÃO DO ESTOQUE DERIVADO
-- ============================================================================

create or replace function public.sincronizar_estoque_compartilhado(
  p_estoque_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.produtos as p
  set estoque =
    (
      e.quantidade_total /
      c.quantidade_por_venda
    )::integer
  from public.produto_estoque_config as c
  join public.estoques_compartilhados as e
    on e.id = c.estoque_compartilhado_id
  where
    p.id = c.produto_id
    and e.id = p_estoque_id;
end;
$$;


-- ============================================================================
-- 4. FUNÇÕES DOS TRIGGERS DE SINCRONIZAÇÃO
-- ============================================================================

create or replace function public.trg_sincronizar_estoque_compartilhado()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.sincronizar_estoque_compartilhado(new.id);
  return new;
end;
$$;


create or replace function public.trg_produto_estoque_config_sync()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'DELETE' then
    update public.produtos
    set estoque = 0
    where id = old.produto_id;

    perform public.sincronizar_estoque_compartilhado(
      old.estoque_compartilhado_id
    );

    return old;
  end if;

  if tg_op = 'UPDATE'
     and old.estoque_compartilhado_id
         <> new.estoque_compartilhado_id then
    perform public.sincronizar_estoque_compartilhado(
      old.estoque_compartilhado_id
    );
  end if;

  perform public.sincronizar_estoque_compartilhado(
    new.estoque_compartilhado_id
  );

  return new;
end;
$$;


-- ============================================================================
-- 5. TRIGGERS DE SINCRONIZAÇÃO
-- ============================================================================

drop trigger if exists trg_estoques_compartilhados_sync
  on public.estoques_compartilhados;

create trigger trg_estoques_compartilhados_sync
after insert or update
on public.estoques_compartilhados
for each row
execute function public.trg_sincronizar_estoque_compartilhado();


drop trigger if exists trg_produto_estoque_config_sync
  on public.produto_estoque_config;

create trigger trg_produto_estoque_config_sync
after insert or delete or update
on public.produto_estoque_config
for each row
execute function public.trg_produto_estoque_config_sync();


-- ============================================================================
-- 6. PROCESSAMENTO DO ESTOQUE FÍSICO EM UMA VENDA
-- ============================================================================

create or replace function public.processar_estoque_compartilhado_pedido(
  p_itens jsonb,
  p_pedido_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_demanda record;
  v_quantidade_anterior integer;
  v_quantidade_nova integer;
begin
  if p_itens is null
     or jsonb_typeof(p_itens) <> 'array' then
    raise exception
      'ITENS_ESTOQUE_COMPARTILHADO_INVALIDOS';
  end if;

  for v_demanda in
    with itens_agrupados as (
      select
        item.id as produto_id,
        sum(item.quantidade)::integer as quantidade
      from jsonb_to_recordset(p_itens)
        as item(
          id bigint,
          quantidade integer,
          opcoes_selecionadas jsonb
        )
      group by item.id
    )
    select
      c.estoque_compartilhado_id,
      sum(
        i.quantidade *
        c.quantidade_por_venda
      )::integer as unidades_necessarias
    from itens_agrupados i
    join public.produto_estoque_config c
      on c.produto_id = i.produto_id
    group by c.estoque_compartilhado_id
    order by c.estoque_compartilhado_id
  loop
    select e.quantidade_total
    into v_quantidade_anterior
    from public.estoques_compartilhados e
    where e.id =
      v_demanda.estoque_compartilhado_id
    for update;

    if not found then
      raise exception
        'ESTOQUE_COMPARTILHADO_NAO_ENCONTRADO:%',
        v_demanda.estoque_compartilhado_id;
    end if;

    if v_quantidade_anterior
       < v_demanda.unidades_necessarias then
      raise exception
        'ESTOQUE_COMPARTILHADO_INSUFICIENTE:%:%',
        v_demanda.estoque_compartilhado_id,
        v_quantidade_anterior;
    end if;

    v_quantidade_nova :=
      v_quantidade_anterior
      - v_demanda.unidades_necessarias;

    update public.estoques_compartilhados as e
    set quantidade_total =
      v_quantidade_nova
    where e.id =
      v_demanda.estoque_compartilhado_id;

    insert into public.movimentacoes_estoque_compartilhado (
      estoque_compartilhado_id,
      pedido_id,
      quantidade_anterior,
      quantidade_nova,
      unidades_consumidas,
      observacao
    )
    values (
      v_demanda.estoque_compartilhado_id,
      p_pedido_id,
      v_quantidade_anterior,
      v_quantidade_nova,
      v_demanda.unidades_necessarias,
      'Venda do pedido #' || p_pedido_id
    );
  end loop;
end;
$$;


-- ============================================================================
-- 7. ENTRADA DE MERCADORIA
-- ============================================================================

create or replace function public.registrar_entrada_estoque(
  p_produto_id bigint,
  p_quantidade integer,
  p_observacao text default null::text
)
returns table(
  produto_id bigint,
  estoque_anterior integer,
  estoque_novo integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_estoque_anterior integer;
  v_estoque_novo integer;
  v_estoque_compartilhado_id bigint;
  v_quantidade_por_venda integer;
  v_quantidade_base_anterior integer;
  v_quantidade_base_nova integer;
  v_quantidade_base_adicionada integer;
  v_observacao text;
begin
  if p_quantidade is null
     or p_quantidade <= 0 then
    raise exception 'QUANTIDADE_INVALIDA';
  end if;

  v_observacao :=
    coalesce(
      nullif(trim(p_observacao), ''),
      'Entrada de mercadoria'
    );

  select
    c.estoque_compartilhado_id,
    c.quantidade_por_venda
  into
    v_estoque_compartilhado_id,
    v_quantidade_por_venda
  from public.produtos p
  left join public.produto_estoque_config c
    on c.produto_id = p.id
  where p.id = p_produto_id;

  if not found then
    raise exception 'PRODUTO_NAO_ENCONTRADO';
  end if;

  if v_estoque_compartilhado_id is not null then
    select e.quantidade_total
    into v_quantidade_base_anterior
    from public.estoques_compartilhados e
    where e.id = v_estoque_compartilhado_id
    for update;

    if not found then
      raise exception
        'ESTOQUE_COMPARTILHADO_NAO_ENCONTRADO:%',
        v_estoque_compartilhado_id;
    end if;

    select p.estoque
    into v_estoque_anterior
    from public.produtos p
    where p.id = p_produto_id
    for update;

    v_quantidade_base_adicionada :=
      p_quantidade * v_quantidade_por_venda;

    v_quantidade_base_nova :=
      v_quantidade_base_anterior
      + v_quantidade_base_adicionada;

    update public.estoques_compartilhados as e
    set quantidade_total =
      v_quantidade_base_nova
    where e.id =
      v_estoque_compartilhado_id;

    select p.estoque
    into v_estoque_novo
    from public.produtos p
    where p.id = p_produto_id;

    insert into public.movimentacoes_estoque_compartilhado (
      estoque_compartilhado_id,
      pedido_id,
      quantidade_anterior,
      quantidade_nova,
      unidades_consumidas,
      observacao
    )
    values (
      v_estoque_compartilhado_id,
      null,
      v_quantidade_base_anterior,
      v_quantidade_base_nova,
      0,
      v_observacao
        || ' | Entrada física: +'
        || v_quantidade_base_adicionada
        || ' unidades'
    );

    insert into public.movimentacoes_estoque (
      produto_id,
      pedido_id,
      tipo,
      quantidade,
      estoque_anterior,
      estoque_novo,
      observacao
    )
    values (
      p_produto_id,
      null,
      'entrada',
      p_quantidade,
      v_estoque_anterior,
      v_estoque_novo,
      v_observacao
        || ' | Estoque compartilhado: +'
        || v_quantidade_base_adicionada
        || ' unidades físicas'
    );

    return query
    select
      p_produto_id,
      v_estoque_anterior,
      v_estoque_novo;

    return;
  end if;

  select p.estoque
  into v_estoque_anterior
  from public.produtos p
  where p.id = p_produto_id
  for update;

  if not found then
    raise exception 'PRODUTO_NAO_ENCONTRADO';
  end if;

  v_estoque_novo :=
    v_estoque_anterior
    + p_quantidade;

  insert into public.movimentacoes_estoque (
    produto_id,
    pedido_id,
    tipo,
    quantidade,
    estoque_anterior,
    estoque_novo,
    observacao
  )
  values (
    p_produto_id,
    null,
    'entrada',
    p_quantidade,
    v_estoque_anterior,
    v_estoque_novo,
    v_observacao
  );

  update public.produtos
  set estoque = v_estoque_novo
  where id = p_produto_id;

  return query
  select
    p_produto_id,
    v_estoque_anterior,
    v_estoque_novo;
end;
$$;


-- ============================================================================
-- 8. CADASTRO / EDIÇÃO DE ESTOQUE COMPARTILHADO PELO ADMIN
-- ============================================================================

create or replace function public.salvar_estoque_compartilhado_admin(
  p_estoque_id bigint,
  p_nome text,
  p_quantidade_total integer,
  p_vinculos jsonb
)
returns table(
  estoque_id bigint,
  nome text,
  quantidade_total integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_estoque_id bigint;
  v_quantidade_anterior integer := 0;
begin
  if nullif(trim(p_nome), '') is null then
    raise exception 'NOME_ESTOQUE_INVALIDO';
  end if;

  if p_quantidade_total is null
     or p_quantidade_total < 0 then
    raise exception 'QUANTIDADE_ESTOQUE_INVALIDA';
  end if;

  if p_vinculos is null
     or jsonb_typeof(p_vinculos) <> 'array' then
    raise exception 'VINCULOS_INVALIDOS';
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(p_vinculos)
      as v(
        produto_id bigint,
        quantidade_por_venda integer
      )
    where v.produto_id is null
       or v.produto_id <= 0
       or v.quantidade_por_venda is null
       or v.quantidade_por_venda <= 0
  ) then
    raise exception 'VINCULO_INVALIDO';
  end if;

  if exists (
    select 1
    from (
      select
        v.produto_id,
        count(*) as quantidade
      from jsonb_to_recordset(p_vinculos)
        as v(
          produto_id bigint,
          quantidade_por_venda integer
        )
      group by v.produto_id
      having count(*) > 1
    ) duplicados
  ) then
    raise exception 'PRODUTO_DUPLICADO_NOS_VINCULOS';
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(p_vinculos)
      as v(
        produto_id bigint,
        quantidade_por_venda integer
      )
    left join public.produtos p
      on p.id = v.produto_id
    where p.id is null
  ) then
    raise exception 'PRODUTO_NAO_ENCONTRADO';
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(p_vinculos)
      as v(
        produto_id bigint,
        quantidade_por_venda integer
      )
    join public.produto_estoque_config c
      on c.produto_id = v.produto_id
    where p_estoque_id is null
       or c.estoque_compartilhado_id <> p_estoque_id
  ) then
    raise exception 'PRODUTO_JA_VINCULADO_OUTRO_ESTOQUE';
  end if;

  if p_estoque_id is null then
    insert into public.estoques_compartilhados (
      nome,
      quantidade_total
    )
    values (
      trim(p_nome),
      p_quantidade_total
    )
    returning id
    into v_estoque_id;

    v_quantidade_anterior := 0;
  else
    select e.quantidade_total
    into v_quantidade_anterior
    from public.estoques_compartilhados e
    where e.id = p_estoque_id
    for update;

    if not found then
      raise exception 'ESTOQUE_COMPARTILHADO_NAO_ENCONTRADO';
    end if;

    v_estoque_id := p_estoque_id;

    update public.estoques_compartilhados as e
    set
      nome = trim(p_nome),
      quantidade_total = p_quantidade_total
    where e.id = v_estoque_id;
  end if;

  delete from public.produto_estoque_config c
  where c.estoque_compartilhado_id = v_estoque_id
    and not exists (
      select 1
      from jsonb_to_recordset(p_vinculos)
        as v(
          produto_id bigint,
          quantidade_por_venda integer
        )
      where v.produto_id = c.produto_id
    );

  insert into public.produto_estoque_config (
    produto_id,
    estoque_compartilhado_id,
    quantidade_por_venda
  )
  select
    v.produto_id,
    v_estoque_id,
    v.quantidade_por_venda
  from jsonb_to_recordset(p_vinculos)
    as v(
      produto_id bigint,
      quantidade_por_venda integer
    )
  on conflict (produto_id)
  do update set
    estoque_compartilhado_id =
      excluded.estoque_compartilhado_id,
    quantidade_por_venda =
      excluded.quantidade_por_venda;

  perform public.sincronizar_estoque_compartilhado(
    v_estoque_id
  );

  if p_estoque_id is null
     or v_quantidade_anterior <> p_quantidade_total then
    insert into public.movimentacoes_estoque_compartilhado (
      estoque_compartilhado_id,
      pedido_id,
      quantidade_anterior,
      quantidade_nova,
      unidades_consumidas,
      observacao
    )
    values (
      v_estoque_id,
      null,
      v_quantidade_anterior,
      p_quantidade_total,
      0,
      case
        when p_estoque_id is null
        then 'Cadastro inicial do estoque físico'
        else 'Ajuste manual do estoque físico pelo administrador'
      end
    );
  end if;

  return query
  select
    e.id,
    e.nome,
    e.quantidade_total
  from public.estoques_compartilhados e
  where e.id = v_estoque_id;
end;
$$;


-- ============================================================================
-- 9. PROTEÇÃO GLOBAL DO ESTOQUE DERIVADO
-- ============================================================================

create or replace function public.proteger_estoque_derivado()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_estoque_calculado integer;
begin
  select
    (
      e.quantidade_total /
      c.quantidade_por_venda
    )::integer
  into v_estoque_calculado
  from public.produto_estoque_config c
  join public.estoques_compartilhados e
    on e.id = c.estoque_compartilhado_id
  where c.produto_id = new.id;

  if found then
    new.estoque := v_estoque_calculado;
  end if;

  return new;
end;
$$;


drop trigger if exists trg_proteger_estoque_derivado
  on public.produtos;

create trigger trg_proteger_estoque_derivado
before update of estoque
on public.produtos
for each row
execute function public.proteger_estoque_derivado();


-- ============================================================================
-- 10. EDIÇÃO DE PRODUTO PELO ADMIN
-- ============================================================================

create or replace function public.atualizar_produto_admin(
  p_produto_id bigint,
  p_nome text,
  p_descricao text,
  p_categoria_id bigint,
  p_preco numeric,
  p_preco_promocional numeric,
  p_estoque integer,
  p_imagem_url text,
  p_ativo boolean,
  p_destaque boolean,
  p_em_promocao boolean,
  p_estoque_minimo integer,
  p_permite_abaixo_minimo boolean
)
returns table(
  id bigint,
  nome text,
  descricao text,
  preco numeric,
  preco_promocional numeric,
  estoque integer,
  estoque_minimo integer,
  imagem_url text,
  ativo boolean,
  destaque boolean,
  em_promocao boolean,
  permite_abaixo_minimo boolean,
  categoria_id bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_estoque_anterior integer;
  v_estoque_final integer;
  v_diferenca integer;
  v_usa_estoque_compartilhado boolean;
begin
  if p_estoque is null or p_estoque < 0 then
    raise exception 'ESTOQUE_INVALIDO';
  end if;

  if p_estoque_minimo is null or p_estoque_minimo < 0 then
    raise exception 'ESTOQUE_MINIMO_INVALIDO';
  end if;

  select
    p.estoque,
    exists (
      select 1
      from public.produto_estoque_config c
      where c.produto_id = p.id
    )
  into
    v_estoque_anterior,
    v_usa_estoque_compartilhado
  from public.produtos p
  where p.id = p_produto_id
  for update;

  if not found then
    raise exception 'PRODUTO_NAO_ENCONTRADO';
  end if;

  if v_usa_estoque_compartilhado then
    v_estoque_final := v_estoque_anterior;
  else
    v_estoque_final := p_estoque;
  end if;

  v_diferenca :=
    v_estoque_final - v_estoque_anterior;

  update public.produtos p
  set
    nome = p_nome,
    descricao = p_descricao,
    categoria_id = p_categoria_id,
    preco = p_preco,
    preco_promocional = p_preco_promocional,
    estoque = v_estoque_final,
    estoque_minimo = p_estoque_minimo,
    imagem_url = p_imagem_url,
    ativo = p_ativo,
    destaque = p_destaque,
    em_promocao = p_em_promocao,
    permite_abaixo_minimo =
      coalesce(p_permite_abaixo_minimo, false)
  where p.id = p_produto_id;

  if not v_usa_estoque_compartilhado
     and v_diferenca <> 0 then
    insert into public.movimentacoes_estoque (
      produto_id,
      pedido_id,
      tipo,
      quantidade,
      estoque_anterior,
      estoque_novo,
      observacao
    )
    values (
      p_produto_id,
      null,
      'ajuste_manual',
      v_diferenca,
      v_estoque_anterior,
      v_estoque_final,
      'Ajuste manual pelo painel administrativo'
    );
  end if;

  return query
  select
    p.id,
    p.nome,
    p.descricao,
    p.preco,
    p.preco_promocional,
    p.estoque,
    p.estoque_minimo,
    p.imagem_url,
    p.ativo,
    p.destaque,
    p.em_promocao,
    p.permite_abaixo_minimo,
    p.categoria_id
  from public.produtos p
  where p.id = p_produto_id;
end;
$$;


-- ============================================================================
-- 11. CRIAÇÃO DE PEDIDO COM ESTOQUE COMPARTILHADO
-- ============================================================================

create or replace function public.criar_pedido_com_estoque_v2(
  p_nome text,
  p_telefone text,
  p_cep text,
  p_rua text,
  p_numero text,
  p_complemento text,
  p_bairro text,
  p_referencia text,
  p_forma_pagamento text,
  p_troco_para numeric,
  p_itens jsonb,
  p_pontos_fidelidade integer,
  p_codigo_cupom text,
  p_chave_idempotencia uuid
)
returns table(
  pedido_id bigint,
  codigo_acesso uuid,
  subtotal numeric,
  taxa_entrega numeric,
  total numeric
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_pedido_existente record;
  v_resultado record;
begin
  if p_chave_idempotencia is null then
    raise exception 'CHAVE_IDEMPOTENCIA_INVALIDA';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(
      p_chave_idempotencia::text,
      0
    )
  );

  select
    p.id,
    p.codigo_acesso,
    p.subtotal,
    p.taxa_entrega,
    p.total
  into v_pedido_existente
  from public.pedidos p
  where p.chave_idempotencia =
    p_chave_idempotencia
  limit 1;

  if found then
    return query
    select
      v_pedido_existente.id,
      v_pedido_existente.codigo_acesso,
      v_pedido_existente.subtotal,
      v_pedido_existente.taxa_entrega,
      v_pedido_existente.total;

    return;
  end if;

  perform e.id
  from public.estoques_compartilhados e
  where e.id in (
    select distinct
      c.estoque_compartilhado_id
    from public.produto_estoque_config c
    join jsonb_to_recordset(p_itens)
      as item(
        id bigint,
        quantidade integer,
        opcoes_selecionadas jsonb
      )
      on item.id = c.produto_id
  )
  order by e.id
  for update of e;

  select *
  into v_resultado
  from public.criar_pedido_com_estoque(
    p_nome,
    p_telefone,
    p_cep,
    p_rua,
    p_numero,
    p_complemento,
    p_bairro,
    p_referencia,
    p_forma_pagamento,
    p_troco_para,
    p_itens,
    p_pontos_fidelidade,
    p_codigo_cupom,
    p_chave_idempotencia
  );

  perform public.processar_estoque_compartilhado_pedido(
    p_itens,
    v_resultado.pedido_id
  );

  perform public.sincronizar_estoque_compartilhado(
    estoque_id
  )
  from (
    select distinct
      c.estoque_compartilhado_id as estoque_id
    from public.produto_estoque_config c
    join jsonb_to_recordset(p_itens)
      as item(
        id bigint,
        quantidade integer,
        opcoes_selecionadas jsonb
      )
      on item.id = c.produto_id
  ) estoques;

  return query
  select
    v_resultado.pedido_id,
    v_resultado.codigo_acesso,
    v_resultado.subtotal,
    v_resultado.taxa_entrega,
    v_resultado.total;
end;
$$;


-- ============================================================================
-- 12. CANCELAMENTO E REPOSIÇÃO
-- ============================================================================

create or replace function public.cancelar_pedido_repor_estoque(
  p_pedido_id bigint
)
returns table(
  id bigint,
  status text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_status text;
  v_cliente_id bigint;
  v_pontos_fidelidade_usados integer;
  v_desconto_fidelidade numeric(12, 2);
  v_cupom_id uuid;
  v_movimento record;
begin
  select
    p.status,
    p.cliente_id,
    coalesce(p.pontos_fidelidade_usados, 0),
    coalesce(p.desconto_fidelidade, 0),
    p.cupom_id
  into
    v_status,
    v_cliente_id,
    v_pontos_fidelidade_usados,
    v_desconto_fidelidade,
    v_cupom_id
  from public.pedidos as p
  where p.id = p_pedido_id
  for update;

  if not found then
    raise exception 'PEDIDO_NAO_ENCONTRADO';
  end if;

  if v_status = 'cancelado' then
    return query
    select
      p.id,
      p.status
    from public.pedidos as p
    where p.id = p_pedido_id;

    return;
  end if;

  if v_status = 'entregue' then
    raise exception
      'PEDIDO_ENTREGUE_NAO_PODE_SER_CANCELADO';
  end if;

  if v_pontos_fidelidade_usados > 0 then
    update public.clientes as c
    set pontos_saldo =
      c.pontos_saldo + v_pontos_fidelidade_usados
    where c.id = v_cliente_id;

    if not found then
      raise exception
        'CLIENTE_NAO_ENCONTRADO:%',
        v_cliente_id;
    end if;

    insert into public.fidelidade_movimentacoes (
      cliente_id,
      pedido_id,
      tipo,
      pontos,
      valor_referencia,
      observacao
    )
    values (
      v_cliente_id,
      p_pedido_id,
      'ajuste_credito',
      v_pontos_fidelidade_usados,
      v_desconto_fidelidade,
      'Estorno de fidelidade por cancelamento do pedido #'
        || p_pedido_id
    );
  end if;

  if v_cupom_id is not null then
    update public.cupons as c
    set
      ativo = (c.valido_ate > now()),
      usado_em = null,
      pedido_id_usado = null
    where c.id = v_cupom_id
      and c.pedido_id_usado = p_pedido_id;
  end if;

  for v_movimento in
    select
      m.estoque_compartilhado_id,
      sum(m.unidades_consumidas)::integer
        as unidades_devolver
    from public.movimentacoes_estoque_compartilhado as m
    where m.pedido_id = p_pedido_id
      and m.unidades_consumidas > 0
    group by m.estoque_compartilhado_id
    order by m.estoque_compartilhado_id
  loop
    declare
      v_quantidade_anterior integer;
      v_quantidade_nova integer;
    begin
      select
        e.quantidade_total
      into
        v_quantidade_anterior
      from public.estoques_compartilhados as e
      where e.id =
        v_movimento.estoque_compartilhado_id
      for update;

      if not found then
        raise exception
          'ESTOQUE_COMPARTILHADO_NAO_ENCONTRADO:%',
          v_movimento.estoque_compartilhado_id;
      end if;

      v_quantidade_nova :=
        v_quantidade_anterior
        + v_movimento.unidades_devolver;

      update public.estoques_compartilhados as e
      set quantidade_total =
        v_quantidade_nova
      where e.id =
        v_movimento.estoque_compartilhado_id;

      insert into public.movimentacoes_estoque_compartilhado (
        estoque_compartilhado_id,
        pedido_id,
        quantidade_anterior,
        quantidade_nova,
        unidades_consumidas,
        observacao
      )
      values (
        v_movimento.estoque_compartilhado_id,
        p_pedido_id,
        v_quantidade_anterior,
        v_quantidade_nova,
        0,
        'Cancelamento do pedido #'
          || p_pedido_id
          || ' | Devolução física: +'
          || v_movimento.unidades_devolver
          || ' unidades'
      );
    end;
  end loop;

  for v_movimento in
    select
      c.estoque_compartilhado_id,
      sum(
        ip.quantidade *
        c.quantidade_por_venda
      )::integer as unidades_devolver
    from public.itens_pedido as ip
    join public.produto_estoque_config as c
      on c.produto_id = ip.produto_id
    where ip.pedido_id = p_pedido_id
      and not exists (
        select 1
        from public.movimentacoes_estoque_compartilhado as m
        where m.pedido_id = p_pedido_id
          and m.estoque_compartilhado_id =
            c.estoque_compartilhado_id
          and m.unidades_consumidas > 0
      )
    group by c.estoque_compartilhado_id
    order by c.estoque_compartilhado_id
  loop
    declare
      v_quantidade_anterior integer;
      v_quantidade_nova integer;
    begin
      select
        e.quantidade_total
      into
        v_quantidade_anterior
      from public.estoques_compartilhados as e
      where e.id =
        v_movimento.estoque_compartilhado_id
      for update;

      if not found then
        raise exception
          'ESTOQUE_COMPARTILHADO_NAO_ENCONTRADO:%',
          v_movimento.estoque_compartilhado_id;
      end if;

      v_quantidade_nova :=
        v_quantidade_anterior
        + v_movimento.unidades_devolver;

      update public.estoques_compartilhados as e
      set quantidade_total =
        v_quantidade_nova
      where e.id =
        v_movimento.estoque_compartilhado_id;

      insert into public.movimentacoes_estoque_compartilhado (
        estoque_compartilhado_id,
        pedido_id,
        quantidade_anterior,
        quantidade_nova,
        unidades_consumidas,
        observacao
      )
      values (
        v_movimento.estoque_compartilhado_id,
        p_pedido_id,
        v_quantidade_anterior,
        v_quantidade_nova,
        0,
        'Cancelamento do pedido #'
          || p_pedido_id
          || ' | Devolução física de pedido legado: +'
          || v_movimento.unidades_devolver
          || ' unidades'
      );
    end;
  end loop;

  insert into public.movimentacoes_estoque (
    produto_id,
    pedido_id,
    tipo,
    quantidade,
    estoque_anterior,
    estoque_novo,
    observacao
  )
  select
    p.id,
    p_pedido_id,
    'cancelamento',
    itens.quantidade_total,
    p.estoque,
    p.estoque + itens.quantidade_total,
    'Cancelamento do pedido #'
      || p_pedido_id
  from public.produtos as p
  join (
    select
      ip.produto_id,
      sum(ip.quantidade)::integer
        as quantidade_total
    from public.itens_pedido as ip
    where ip.pedido_id = p_pedido_id
    group by ip.produto_id
  ) as itens
    on itens.produto_id = p.id
  left join public.produto_estoque_config as c
    on c.produto_id = p.id
  where c.produto_id is null;

  update public.produtos as p
  set estoque =
    p.estoque + itens.quantidade_total
  from (
    select
      ip.produto_id,
      sum(ip.quantidade)::integer
        as quantidade_total
    from public.itens_pedido as ip
    where ip.pedido_id = p_pedido_id
    group by ip.produto_id
  ) as itens
  left join public.produto_estoque_config as c
    on c.produto_id = itens.produto_id
  where p.id = itens.produto_id
    and c.produto_id is null;

  update public.pedidos as p
  set status = 'cancelado'
  where p.id = p_pedido_id;

  return query
  select
    p.id,
    p.status
  from public.pedidos as p
  where p.id = p_pedido_id;
end;
$$;


-- ============================================================================
-- 13. PERMISSÕES DOS RPCs NOVOS / INTERNOS
-- ============================================================================

revoke all on function public.sincronizar_estoque_compartilhado(bigint)
  from public;

revoke all on function public.processar_estoque_compartilhado_pedido(jsonb, bigint)
  from public;

revoke all on function public.registrar_entrada_estoque(bigint, integer, text)
  from public;

revoke all on function public.salvar_estoque_compartilhado_admin(bigint, text, integer, jsonb)
  from public;

revoke all on function public.criar_pedido_com_estoque_v2(
  text, text, text, text, text, text, text, text, text,
  numeric, jsonb, integer, text, uuid
)
from public;

revoke all on function public.cancelar_pedido_repor_estoque(bigint)
  from public;

grant execute on function public.sincronizar_estoque_compartilhado(bigint)
  to service_role;

grant execute on function public.processar_estoque_compartilhado_pedido(jsonb, bigint)
  to service_role;

grant execute on function public.registrar_entrada_estoque(bigint, integer, text)
  to service_role;

grant execute on function public.salvar_estoque_compartilhado_admin(bigint, text, integer, jsonb)
  to service_role;

grant execute on function public.criar_pedido_com_estoque_v2(
  text, text, text, text, text, text, text, text, text,
  numeric, jsonb, integer, text, uuid
)
to service_role;

grant execute on function public.cancelar_pedido_repor_estoque(bigint)
  to service_role;


-- ============================================================================
-- 14. SINCRONIZA O QUE JÁ ESTIVER VINCULADO
-- ============================================================================

do $$
declare
  v_estoque record;
begin
  for v_estoque in
    select e.id
    from public.estoques_compartilhados e
    order by e.id
  loop
    perform public.sincronizar_estoque_compartilhado(
      v_estoque.id
    );
  end loop;
end;
$$;

-- ============================================================================
-- FIM
-- ============================================================================
